# Generated by Django 5.0.3 on 2024-04-12 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 14, 16, 53, 620451, tzinfo=datetime.timezone.utc)),
        ),
    ]
